//all of the words, in korean and english that are being taught
var wordDict = [
    ['the', '그만큼'],
    ['of', '의'],
    ['and', '그리고'],
    ['a', 'ㅏ'],
    ['to', '에게'],
    ['in', '~에'],
    ['is', ''],
    ['you', '너'],
    ['that', '저것'],
    ['it', '그것'],
    ['he', '그'],
    ['was', '~였다'],
    ['for', '~을위한'],
    ['on', '켜짐'],
    ['are', '~이다'],
    ['as', '~처럼'],
    ['with', '~와 함께'],
    ['his', '그의'],
    ['they', '그들'],
    ['i', '나'],
    ['at', '~에'],
    ['this', '이것'],
    ['have', '가지다'],
    ['from', '~에서'],
    ['or', '또는'],
    ['one', '하나'],
    ['had', '가졌다'],
    ['by', '~에 의해'],
    ['word', '단어'],
    ['but', '하지만'],
    ['not', '~ 아니다'],
    ['what', '무엇'],
    ['all', '모두'],
    ['were', '~이었다'],
    ['we', '우리'],
    ['when', '언제'],
    ['your', '당신의'],
    ['can', '~ 할 수있다'],
    ['said', '말했다'],
    ['there', '거기'],
    ['use', '사용'],
    ['each', '각'],
    ['which', '어느'],
    ['she', '그녀'],
    ['do', '하다'],
    ['how', '어떻게'],
    ['their', '그들의'],
    ['if', '만약'],
    ['will', '~ 할 것이다'],
    ['up', '위로'],
    ['other', '다른'],
    ['about', '~에 대한'],
    ['out', '밖'],
    ['many', '많은'],
    ['then', '그 다음에'],
    ['them', '그들을'],
    ['these', '이것들'],
    ['so', '그래서'],
    ['some', '일부'],
    ['her', '그녀의'],
    ['would', '~ 일 것이다'],
    ['make', '만들다'],
    ['like', '어느'],
    ['him', '그를'],
    ['into', '~ 안으로'],
    ['time', '시각'],
    ['has', '가지다'],
    ['look', '바라보다'],
    ['two', '둘'],
    ['more', '더'],
    ['write', '쓰다'],
    ['go', '가다'],
    ['see', '보다'],
    ['number', '숫자'],
    ['no', '아니요'],
    ['way', '방법'],
    ['could', '~ 할 수 있었다'],
    ['people', '사람들'],
    ['my', '나의'],
    ['than', '~보다'],
    ['first', '첫 번째'],
    ['water', '물'],
    ['been', '계속 ~이다'],
    ['call', '전화'],
    ['oil', '기름'],
    ['its', '그것의'],
    ['now', '어느'],
    ['find', '찾기'],
    ['long', '긴'],
    ['down', '아래에'],
    ['day', '낮'],
    ['did', '했다'],
    ['get', '가져 오기'],
    ['come', '오다'],
    ['made', '만들어진'],
    ['may', '할 수있다'],
    ['part', '부분'],
    ['over', '~ 위에'],
    ['new', '새로운'],
    ['sound', '소리'],
    ['take', '가져 가다'],
    ['only', '오직'],
    ['little', '작은'],
    ['work', '일하다'],
    ['know', '알고있다'],
    ['place', '장소'],
    ['year', '년도'],
    ['live', '라이브'],
    ['me', '나'],
    ['back', '뒤'],
    ['give', '주다'],
    ['most', '최대'],
    ['very', '매우'],
    ['after', '~ 후에'],
    ['thing', '물건'],
    ['our', '우리의'],
    ['just', '단지'],
    ['name', '이름'],
    ['good', '좋은'],
    ['sentence', '문장'],
    ['man', '남성'],
    ['think', '생각한다'],
    ['say', '말하다'],
    ['great', '엄청난'],
    ['where', '엄청난'],
    ['help', '돕다'],
    ['through', '~을 통해'],
    ['line', '라인'],
    ['right', '오른쪽'],
    ['too', '~도'],
    ['mean', '평균'],
    ['old', '낡은'],
    ['any', '어느'],
    ['same', '같은'],
    ['tell', '말하다'],
    ['boy', '소년'],
    ['follow', '따르다'],
    ['came', '왔다'],
    ['want', '원하다'],
    ['show', '보여 주다'],
    ['also', '또한'],
    ['around', '약'],
    ['from', '~에서'],
    ['three', '삼'],
    ['small', '작은'],
    ['set', '세트'],
    ['put', '놓다'],
    ['end', '끝'],
    ['does', '하다'],
    ['another', '또 다른'],
    ['well', '잘'],
    ['large', '크기가 큰'],
    ['must', '~해야하다'],
    ['big', '큰'],
    ['even', '조차'],
    ['such', '그런'],
    ['because', '왜냐하면'],
    ['turn', '회전하다'],
    ['here', '여기'],
    ['why', '왜'],
    ['ask', '물어보기'],
    ['went', '갔다'],
    ['men', '남자들'],
    ['read', '읽다'],
    ['need', '필요'],
    ['land', '나라'],
    ['different', '다른'],
    ['home', '집'],
    ['us', '우리를'],
    ['move', '이동하다'],
    ['try', '노력하다'],
    ['kind', '친절한'],
    ['hand', '손'],
    ['picture', '그림'],
    ['again', '다시'],
    ['change', '변화'],
    ['off', '끄다'],
    ['play', '플레이'],
    ['spell', '주문'],
    ['air', '공기'],
    ['away', '떨어져있는'],
    ['animal', '동물'],
    ['house', '집'],
    ['point', '가리키다'],
    ['page', '페이지'],
    ['letter', '편지'],
    ['mother', '어머니'],
    ['answer', '대답'],
    ['found', '설립하다'],
    ['study', '공부하다'],
    ['still', '아직'],
    ['learn', '배우다'],
    ['should', '~해야한다'],
    ['america', '미국'],
    ['korea', '한국'],
    ['world', '세계'],
    ['high', '높은'],
    ['every', '모든'],
    ['near', '가까운'],
    ['add', '추가하다'],
    ['food', '음식'],
    ['between', '~ 사이'],
    ['own', '소유하다'],
    ['below', '아래에'],
    ['country', '국가'],
    ['plant', '공장'],
    ['last', '마지막'],
    ['school', '학교'],
    ['father', '아버지'],
    ['keep', '유지하다'],
    ['tree', '나무'],
    ['never', '절대'],
    ['start', '시작'],
    ['city', '도시'],
    ['earth', '지구'],
    ['eye', '눈'],
    ['light', '빛'],
    ['thought', '생각'],
    ['head', '머리'],
    ['under', '아래에'],
    ['story', '이야기'],
    ['saw', '보았다'],
    ['left', '왼쪽'],
    ["don't", '하지마'],
    ['few', '약간의'],
    ['while', '동안'],
    ['along', '~을 따라'],
    ['might', '~ 할 것 같다'],
    ['close', '닫다'],
    ['something', '무엇'],
    ['seem', '~ 인 것 같다'],
    ['next', '다음'],
    ['hard', '딱딱한'],
    ['open', '열려있는'],
    ['example', '예시'],
    ['begin', '시작하다'],
    ['life', '삶'],
    ['always', '언제나'],
    ['those', '저것들'],
    ['both', '둘 다'],
    ['paper', '종이'],
    ['together', '함께'],
    ['got', '갖다'],
    ['group', '그룹'],
    ['often', '자주'],
    ['run', '운영'],
    ['important', '중요한'],
    ['until', '~까지'],
    ['children', '어린이들'],
    ['side', '옆'],
    ['feet', '피트'],
    ['car', '차'],
    ['mile', '마일'],
    ['night', '밤'],
    ['walk', '걷다'],
    ['white', '하얀색'],
    ['sea', '바다'],
    ['began', '시작했다'],
    ['grow', '자라다'],
    ['took', '가지고 갔다'],
    ['river', '강'],
    ['four', '네'],
    ['carry', '나르다'],
    ['state', '상태'],
    ['once', '한번'],
    ['book', '책'],
    ['hear', '듣다'],
    ['stop', '그만'],
    ['without', '없이'],
    ['second', '둘째'],
    ['miss', '놓치다'],
    ['idea', '아이디어'],
    ['enough', '충분한'],
    ['eat', '먹다'],
    ['face', '얼굴'],
    ['watch', '보다'],
    ['far', '멀리'],
    ['indian', '인도 사람'],
    ['really', '정말로'],
    ['almost', '거의'],
    ['let', '허락하다'],
    ['above', '~ 위에'],
    ['girl', '여자'],
    ['sometimes', '때때로'],
    ['mountain', '산'],
    ['cut', '자르다'],
    ['young', '어린'],
    ['talk', '말하다'],
    ['soon', '곧'],
    ['list', '곧'],
    ['song', '노래'],
    ['being', '존재'],
    ['leave', '떠나다'],
    ['family', '가족'],
    ["it's", '그것은'],
    ['body', '몸'],
    ['music', '음악'],
    ['color', '색상'],
    ['stand', '서다'],
    ['sun', '태양'],
    ['question', '의문'],
    ['fish', '물고기'],
    ['area', '지역'],
    ['mark', '표시'],
    ['dog', '개'],
    ['horse', '말'],
    ['birds', '조류'],
    ['problem', '문제'],
    ['complete', '완벽한'],
    ['room', '방'],
    ['knew', '알고 있었다'],
    ['since', '~부터'],
    ['ever', '항상'],
    ['piece', '조각'],
    ['told', '말했다'],
    ['usually', '대개'],
    ["didn't", '하지 않았다'],
    ['friends', '친구'],
    ['easy', '쉬운'],
    ['heard', '들었다'],
    ['order', '주문하다'],
    ['red', '빨간색'],
    ['door', '문'],
    ['sure', '확실한'],
    ['become', '~이되다'],
    ['top', '맨 위'],
    ['ship', '배'],
    ['across', '가로 질러'],
    ['today', '오늘'],
    ['during', '~ 동안'],
    ['short', '짧은'],
    ['better', '더 나은'],
    ['best', '베스트'],
    ['however', '하지만'],
    ['low', '낮은'],
    ['hours', '시간'],
    ['black', '검은 색'],
    ['products', '제품'],
    ['happened', '일어난'],
    ['whole', '전체'],
    ['measure', '측정하다'],
    ['remember', '기억하다'],
    ['early', '일찍'],
    ['waves', '파도'],
    ['reached', '도달했다'],
    ['listen', '듣다'],
    ['wind', '듣다'],
    ['rock', '바위'],
    ['space', '공간'],
    ['covered', '덮인'],
    ['fast', '빠른'],
    ['several', '몇몇의'],
    ['hold', '잡고있다'],
    ['himself', '그 자신'],
    ['toward', '~을 향하여'],
    ['five', '다섯'],
    ['step', '단계'],
    ['morning', '아침'],
    ['passed', '통과'],
    ['vowel', '모음'],
    ['true', '진실'],
    ['hundred', '백'],
    ['against', '~에 맞서'],
    ['pattern', '무늬'],
    ['numeral', '숫자'],
    ['table', '테이블'],
    ['north', '북쪽'],
    ['slowly', '느리게'],
    ['money', '돈'],
    ['map', '지도'],
    ['farm', '농장'],
    ['pulled', '당겨'],
    ['draw', '그리다'],
    ['voice', '목소리'],
    ['seen', '본'],
    ['cold', '추운'],
    ['cried', '울었다'],
    ['plan', '계획'],
    ['notice', '알아 채다'],
    ['south', '남쪽'],
    ['sing', '노래'],
    ['war', '전쟁'],
    ['ground', '지면'],
    ['fall', '떨어지다'],
    ['king', '왕'],
    ['town', '도시'],
    ["i'll", '아픈'],
    ['unit', '단위'],
    ['figure', '수치'],
    ['certain', '서틴'],
    ['field', '들'],
    ['travel', '여행하다'],
    ['wood', '목재'],
    ['fire', '불'],
    ['done', '완료'],
    ['english', '영어'],
    ['road', '도로'],
    ['halt', '정지'],
    ['ten', '십'],
    ['fly', '파리'],
    ['gave', '준'],
    ['box', '상자'],
    ['finally', '마지막으로'],
    ['wait', '마지막으로'],
    ['correct', '옳은'],
    ['oh', '오'],
    ['quickly', '빠르게'],
    ['person', '사람'],
    ['became', '~가되었다'],
    ['shown', '표시'],
    ['minutes', '분'],
    ['strong', '강한'],
    ['verb', '동사'],
    ['stars', '별'],
    ['front', '앞'],
    ['feel', '느끼다'],
    ['fact', '사실'],
    ['inches', '신장'],
    ['street', '거리'],
    ['decided', '결정했다'],
    ['contain', '포함하다'],
    ['course', '강좌'],
    ['surface', '표면'],
    ['produce', '생산하다'],
    ['building', '건물'],
    ['ocean', '대양'],
    ['class', '등급'],
    ['note', '노트'],
    ['nothing', '아무것도 아님'],
    ['rest', '쉬다'],
    ['carefully', '주의하여'],
    ['scientists', '과학자들'],
    ['inside', '내부에'],
    ['wheels', '바퀴'],
    ['stay', '머무르다'],
    ['green', '초록'],
    ['known', '모두 다 아는'],
    ['island', '섬'],
    ['week', '주'],
    ['less', '더 적은'],
    ['machine', '기계'],
    ['base', '베이스'],
    ['ago', '~ 전에'],
    ['stood', '서서'],
    ['plane', '비행기'],
    ['system', '체계'],
    ['behind', '뒤에'],
    ['ran', '달렸다'],
    ['round', '둥근'],
    ['boat', '보트'],
    ['game', '게임'],
    ['force', '힘'],
    ['brought', '가져왔다'],
    ['understand', '이해하다'],
    ['warm', '따뜻한'],
    ['common', '흔한'],
    ['bring', '가져오다'],
    ['explain', '설명'],
    ['dry', '마른'],
    ['though', '~을 통해'],
    ['language', '언어'],
    ['shape', '모양'],
    ['deep', '깊은'],
    ['thousands', '수천'],
    ['yes', '네'],
    ['clear', '분명한'],
    ['equation', '방정식'],
    ['yet', '아직'],
    ['goverment', '정부'],
    ['filled', '채우는'],
    ['heat', '열'],
    ['full', '가득한'],
    ['hot', '더운'],
    ['check', '확인하다'],
    ['object', '물체'],
    ['am', '~이다'],
    ['rule', '규칙'],
    ['among', '의 사이에'],
    ['noun', '명사'],
    ['power', '힘'],
    ['cannot', '할 수 없다'],
    ['able', '할 수있는'],
    ['six', '육'],
    ['size', '크기'],
    ['dark', '어두운'],
    ['ball', '공'],
    ['material', '재료'],
    ['special', '특별한'],
    ['heavy', '무거운'],
    ['fine', '좋아'],
    ['pair', '쌍'],
    ['circle', '원'],
    ['include', '포함하다'],
    ['built', '세워짐'],
    ["can't", '캔트'],
    ['matter', '문제'],
    ['square', '정사각형'],
    ['syllables', '음절'],
    ['perhaps', '아마도'],
    ['bill', '청구서'],
    ['felt', '느꼈다'],
    ['suddenly', '갑자기'],
    ['test', '테스트'],
    ['direction', '방향'],
    ['center', '센터'],
    ['farmers', '농부들'],
    ['ready', '준비가 된'],
    ['anything', '아무것'],
    ['divided', '각기 다른'],
    ['general', '일반'],
    ['energy', '에너지'],
    ['subject', '주제'],
    ['europe', '유럽'],
    ['moon', '달'],
    ['region', '지역'],
    ['believe', '믿다'],
    ['dance', '댄스'],
    ['members', '회원'],
    ['picked', '고른'],
    ['simple', '단순한'],
    ['cells', '세포'],
    ['paint', '페인트'],
    ['mind', '정신'],
    ['love', '사랑'],
    ['cause', '원인'],
    ['rain', '비'],
    ['exercise', '연습'],
    ['eggs', '달걀'],
    ['train', '기차'],
    ['blue', '푸른'],
    ['wish', '소망'],
    ['drop', '하락'],
    ['developed', '개발된'],
    ['window', '창문'],
    ['difference', '차이점'],
    ['distance', '거리'],
    ['heart', '마음'],
    ['sit', '앉다'],
    ['sum', '합집합'],
    ['summer', '여름'],
    ['wall', '벽'],
    ['forest', '숲'],
    ['probally', '아마'],
    ['legs', '다리'],
    ['sat', '수능'],
    ['main', '기본'],
    ['winter', '겨울'],
    ['wide', '넓은'],
    ['written', '쓴'],
    ['length', '길이'],
    ['reason', '이유'],
    ['kept', '유지 된'],
    ['interest', '관심'],
    ['arms', '무기'],
    ['brother', '형제'],
    ['race', '경주'],
    ['present', '현재'],
    ['beautiful', '아름다운'],
    ['store', '가게'],
    ['job', '직업'],
    ['edge', '가장자리'],
    ['past', '과거'],
    ['sign', '징후'],
    ['record', '기록'],
    ['finished', '완성 된'],
    ['discovered', '발견'],
    ['wild', '야생의'],
    ['happy', '행복하다'],
    ['beside', '옆에'],
    ['gone', '다 쓴'],
    ['sky', '하늘'],
    ['glass', '유리'],
    ['million', '백만'],
    ['west', '서쪽'],
    ['lay', '놓다'],
    ['weather', '날씨'],
    ['root', '뿌리'],
    ['instruments', '악기'],
    ['meet', '만나다'],
    ['third', '제삼'],
    ['months', '개월'],
    ['paragraph', '절'],
    ['raised', '높은'],
    ['represent', '대표하다'],
    ['soft', '부드러운'],
    ['whether', '~이든'],
    ['clothes', '옷'],
    ['flowers', '꽃들'],
    ['shall', '~ 일 것이다'],
    ['teacher', '선생님'],
    ['held', '유지 된'],
    ['describe', '설명하다'],
    ['drive', '운전하다'],
    ['cross', '십자가'],
    ['speak', '말하다'],
    ['solve', '해결하다'],
    ['appear', '나타나다'],
    ['metal', '금속'],
    ['son', '아들'],
    ['either', '어느 하나'],
    ['ice', '빙'],
    ['sleep', '잠'],
    ['village', '마을'],
    ['factors', '요인'],
    ['result', '결과'],
    ['jumped', '뛰어 올랐다'],
    ['snow', '눈'],
    ['ride', '타다'],
    ['care', '케어'],
    ['floor', '바닥'],
    ['hill', '언덕'],
    ['pushed', '밀린'],
    ['baby', '아기'],
    ['buy', '구입'],
    ['century', '세기'],
    ['outside', '밖의'],
    ['everything', '모든 것'],
    ['tall', '키가 큰'],
    ['already', '이미'],
    ['instead', '대신에'],
    ['phrase', '구절'],
    ['soil', '토양'],
    ['bed', '침대'],
    ['copy', '복사'],
    ['free', '무료'],
    ['hope', '희망'],
    ['spring', '봄'],
    ['case', '사례'],
    ['laughed', '웃었다'],
    ['nation', '국가'],
    ['quite', '상당히'],
    ['type', '유형'],
    ['themselves', '그들 자신'],
    ['temperature', '온도'],
    ['bright', '밝은'],
    ['lead', '리드'],
    ['everyone', '여러분'],
    ['method', '방법'],
    ['section', '부분'],
    ['lake', '호수'],
    ['consonant', '자음'],
    ['within', '이내에'],
    ['dictionary', '사전'],
    ['hair', '머리카락'],
    ['age', '나이'],
    ['amount', '양'],
    ['scale', '규모'],
    ['pounds', '파운드'],
    ['although', '하지만'],
    ['kilograms', '킬로그램'],
    ['although', '하지만'],
    ['per', '당'],
    ['broken', '고장난'],
    ['moment', '순간'],
    ['tiny', '매우 작은'],
    ['possible', '가능한'],
    ['gold', '금'],
    ['milk', '우유'],
    ['quiet', '조용한'],
    ['natural', '자연스러운'],
    ['lot', '많은'],
    ['stone', '결석'],
    ['act', '행동'],
    ['build', '짓다'],
    ['middle', '가운데'],
    ['speed', '속도'],
    ['count', '세다'],
    ['cat', '고양이'],
    ['someone', '누구'],
    ['sail', '돛'],
    ['rolled', '압연'],
    ['bear', '곰'],
    ['wonder', '궁금하다'],
    ['smiled', '미소지었다'],
    ['angle', '각도'],
    ['fraction', '분수'],
    ['africa', '아프리카'],
    ['killed', '살해'],
    ['melody', '멜로디'],
    ['bottom', '맨 아래'],
    ['trip', '여행'],
    ['hole', '구멍'],
    ['poor', '가난한'],
    ["let's", '하자'],
    ['fight', '싸움'],
    ['surprise', '놀라다'],
    ['french', '프랑스 국민'],
    ['died', '사망 한'],
    ['beat', '이기다'],
    ['exactly', '바로 그거죠'],
    ['remain', '유지하다'],
    ['dress', '드레스'],
    ['iorn', '이오른'],
    ["couldn't", '할 수 없었다'],
    ['fingers', '손가락'],
    ['row', '열'],
    ['least', '최소'],
    ['catch', '잡다'],
    ['climbed', '등반'],
    ['wrote', '썼다'],
    ['shouted', '소리쳤다'],
    ['continued', '계속되는'],
    ['itself', '그 자체'],
    ['else', '또 다른'],
    ['plains', '평원'],
    ['gas', '가스'],
    ['england', '영국'],
    ['burning', '타고 있는'],
    ['design', '설계'],
    ['joined', '합류'],
    ['foot', '발'],
    ['law', '법'],
    ['ears', '귀'],
    ['grass', '잔디'],
    ["you're", '당신은'],
    ['grew', '성장했다'],
    ['skin', '피부'],
    ['valley', '골짜기'],
    ['cents', '센트'],
    ['key', '열쇠'],
    ['president', '대통령'],
    ['brown', '갈색'],
    ['trouble', '문제'],
    ['cool', '시원한'],
    ['cloud', '구름'],
    ['lost', '잃어버린'],
    ['sent', '전송 된'],
    ['symbols', '기호'],
    ['wear', '입다'],
    ['bad', '나쁜'],
    ['save', '저장'],
    ['experiment', '실험'],
    ['engine', '엔진'],
    ['alone', '홀로'],
    ['drawing', '그림'],
    ['east', '동쪽'],
    ['pay', '지불'],
    ['single', '하나의'],
    ['touch', '만지다'],
    ['information', '정보'],
    ['express', '표현하다'],
    ['mouth', '입'],
    ['yard', '마당'],
    ['equal', '동일한'],
    ['decimal', '소수'],
    ['yourself', '당신 자신'],
    ['control', '제어'],
    ['pratice', '관행'],
    ['report', '보고서'],
    ['straight', '똑바로'],
    ['rise', '증가'],
    ['statement', '성명'],
    ['stick', '막대'],
    ['party', '파티'],
    ['seeds', '씨앗'],
    ['suppose', '추정 된'],
    ['woman', '여성'],
    ['coast', '해안'],
    ['bank', '은행'],
    ['period', '기간'],
    ['wire', '철사'],
    ['choose', '선택하다'],
    ['clean', '깨끗한'],
    ['visit', '방문하다'],
    ['bit', '조금'],
    ['whose', '누구의'],
    ['received', '받았다'],
    ['garden', '정원'],
    ['please', '제발'],
    ['strange', '이상한'],
    ['caught', '잡았다'],
    ['fell', '쓰러 뜨리다'],
    ['team', '팀'],
    ['god', '하나님'],
    ['captain', '선장'],
    ['direct', '직접'],
    ['ring', '반지'],
    ['serve', '제공하다'],
    ['child', '아이'],
    ['desert', '사막'],
    ['increase', '증가하다'],
    ['history', '역사'],
    ['cost', '비용'],
    ['maybe', '아마도'],
    ['business', '사업'],
    ['separate', '따로'],
    ['break', '부서지다'],
    ['uncle', '삼촌'],
    ['hunting', '수렵'],
    ['flow', '흐름'],
    ['lady', '숙녀'],
    ['students', '재학생'],
    ['human', '인간'],
    ['art', '미술'],
    ['feeling', '감정'],
    ['supply', '공급'],
    ['corner', '모서리'],
    ['electric', '전기 같은'],
    ['insects', '곤충'],
    ['crops', '작물'],
    ['tone', '음정'],
    ['hit', '때리다'],
    ['sand', '모래'],
    ['doctor', '의사'],
    ['provide', '제공하다'],
    ['thus', '이와 같이'],
    ["won't", '습관'],
    ['cook', '요리하다'],
    ['bones', '뼈'],
    ['tail', '꼬리'],
    ['board', '판자'],
    ['modern', '현대의'],
    ['compound', '화합물'],
    ['mine', '나의 것'],
    ["wasn't", '아니었어'],
    ['fit', '맞다'],
    ['addition', '덧셈'],
    ['belong', '제자리에있다'],
    ['safe', '안전한'],
    ['soldiers', '군인'],
    ['guess', '추측하다'],
    ['silent', '조용한'],
    ['trade', '거래'],
    ['rather', '꽤'],
    ['compare', '비교하다'],
    ['crowd', '군중'],
    ['poem', '시'],
    ['enjoy', '즐겨'],
    ['elements', '집단'],
    ['indicate', '나타내 다'],
    ['except', '제외하고'],
    ['flat', '평평한'],
    ['seven', '일곱'],
    ['interesting', '흥미로운'],
    ['sense', '감각'],
    ['string', '끈'],
    ['blow', '불다'],
    ['famous', '유명한'],
    ['value', '값'],
    ['wings', '날개'],
    ['movement', '움직임'],
    ['pole', '폴'],
    ['exciting', '신나는'],
    ['branches', '가지'],
    ['thick', '두꺼운'],
    ['blood', '피'],
    ['lie', '거짓말하다'],
    ['spot', '점'],
    ['bell', '벨'],
    ['fun', '재미있는'],
    ['loud', '시끄러운'],
    ['consider', '고려하다'],
    ['suggested', '제안'],
    ['thin', '얇은'],
    ['position', '위치'],
    ['entered', '입력'],
    ['fruit', '과일'],
    ['tied', '묶인'],
    ['rich', '부자'],
    ['dollars', '불화'],
    ['send', '보내다'],
    ['sight', '시력'],
    ['cheif', '셰프'],
    ['japanese', '일본어'],
    ['stream', '개울'],
    ['planets', '행성'],
    ['rhythm', '율'],
    ['eight', '여덟'],
    ['science', '과학'],
    ['major', '주요한'],
    ['observe', '관찰하다'],
    ['tube', '튜브'],
    ['necessary', '필요한'],
    ['weight', '무게'],
    ['meat', '고기'],
    ['lifted', '들어 올린'],
    ['process', '프로세스'],
    ['army', '군대'],
    ['hat', '모자'],
    ['property', '재산'],
    ['particular', '특정한'],
    ['swim', '수영'],
    ['terms', '자귀'],
    ['current', '현재의'],
    ['park', '공원'],
    ['sell', '팔다'],
    ['shoulder', '어깨'],
    ['industry', '산업'],
    ['wash', '씻다'],
    ['block', '블록'],
    ['spread', '확산'],
    ['cattle', '가축'],
    ['wife', '부인'],
    ['sharp', '날카로운'],
    ['company', '회사'],
    ['radio', '라디오'],
    ["we'll", '잘'],
    ['action', '동작'],
    ['capital', '수도'],
    ['factories', '공장'],
    ['settled', '안정된'],
    ['yellow', '노랑'],
    ["isn't", '아니다'],
    ['southern', '남부 지방 사투리'],
    ['truck', '트럭'],
    ['fair', '공정한'],
    ['printed', '인쇄'],
    ["wouldn't", '하지 않을 것이다'],
    ['ahead', '앞으로'],
    ['chance', '가능성'],
    ['born', '태어난'],
    ['level', '수준'],
    ['triangle', '삼각형'],
    ['molecules', '분자'],
    ['france', '프랑스'],
    ['repeated', '반복'],
    ['column', '열'],
    ['western', '서부 사람'],
    ['church', '교회'],
    ['coronavirus', '코로나 바이러스'],
    ['sister', '자매'],
    ['oxygen', '산소'],
    ['plural', '복수형'],
    ['various', '다양한'],
    ['agreed', '동의'],
    ['opposite', '반대'],
    ['wrong', '잘못된'],
    ['chart', '차트'],
    ['prepared', '준비된'],
    ['pretty', '예쁜'],
    ['solution', '해결책'],
    ['fresh', '신선한'],
    ['shop', '가게'],
    ['suffix', '접미사'],
    ['especially', '특히'],
    ['shoes', '신발'],
    ['actually', '실제로'],
    ['nose', '코'],
    ['afraid', '두려워하는'],
    ['dead', '죽은'],
    ['sugar', '설탕'],
    ['adjective', '형용사'],
    ['fig', '무화과'],
    ['office', '사무실'],
    ['huge', '거대한'],
    ['gun', '총'],
    ['similar', '비슷한'],
    ['death', '죽음'],
    ['score', '점수'],
    ['forward', '앞으로'],
    ['streched', '뻗어'],
    ['experience', '경험'],
    ['rose', '장미'],
    ['allow', '허용하다'],
    ['fear', '두려움'],
    ['workers', '노동자'],
    ['washington', '워싱턴'],
    ['greek', '그리스 어'],
    ['women', '여성'],
    ['brought', '가져왔다'],
    ['led', '~ 주도의'],
    ['northern', '북부 사투리'],
    ['create', '만들다'],
    ['british', '영국의'],
    ['difficult', '어려운'],
    ['match', '성냥'],
    ['win', '이기다'],
    ["dosen't", '하지마'],
    ['steel', '강철'],
    ['total', '총'],
    ['deal', '거래'],
    ['determine', '결정'],
    ['evening', '저녁'],
    ['rope', '로프'],
    ['cotton', '면'],
    ['apple', '사과'],
    ['details', '세부'],
    ['entire', '전체'],
    ['corn', '옥수수'],
    ['substances', '물질'],
    ['smell', '냄새가 나다'],
    ['tools', '도구'],
    ['conditions', '정황'],
    ['cows', '소'],
    ['track', '길'],
    ['arrived', '도착했다'],
    ['located', '위치한'],
    ['sir', '선생님'],
    ['seat', '좌석'],
    ['division', '분할'],
    ['effect', '효과'],
    ['underline', '밑줄'],
    ['veiw', '봐']
];

function run () {
    const date = new Date();
    let time = date.getTime();

    const minute = 1000 * 60;
    const hour = minute * 60;
    const day = hour * 24;

    let index = Math.round(time / day);
    let moddedIndex = index - Math.floor(index / wordDict.length) * wordDict.length;

    document.getElementById('english').innerHTML = wordDict[moddedIndex][0];
    document.getElementById('korean').innerHTML = wordDict[moddedIndex][1];
    console.log('k');
}

window.setInterval(run(), 10);